version: "3.8"

services:
  app:
    container_name: anistream-content-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8800:8800"
      - "50051:50051"
    environment:
      - CONFIG_PATH=/app/config/local.yml
      - KODIK_TOKEN=${KODIK_TOKEN}
    volumes:
      - /home/bruma/anistream-content/config:/app/config

  redis:
    container_name: anistream-content-cache
    image: redis:7.0.12
    restart: always
    ports:
      - "6380:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  anistream-network:
